language: go

# S: Build Lifecycle
# install
# before_script
# script:

script:
  - ls
  - ink build template
  - ls
  - cd ./template/docs
  - git init
  - git config user.name "shery15"
  - git config user.email "382254994@qq.com"
  - git add .
  - git commit -m "update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# E: Build Lifecycle

branches:
  only:
    - blog-source
env:
  global:
    - GH_REF: github.com/shery15/blog
