site:
    title: "拾光机"
    subtitle: "时间不负，何负时间"
    limit: 10
    theme: theme
    lang: zh
    url: "http://www.shery.me/blog/"
    comment: shery09
    logo: "-/images/logo.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    root: "/blog"

authors:
    me:
        name: "shery"
        intro: "前端攻城狮"
        avatar: "-/images/avatar.png"

build:
    output: "docs"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
        - "README.md"
    # Excuted command when use 'ink publish'
    publish: |
        git add .
        git commit -m "update"
        git push origin blog-source
